version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - POSTGRES_PORT=${DOCKER_PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./:/app/database
    working_dir: /app
    command: python3 -m database.app
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DOCKER_PORT}
    ports:
      - ${HOST_PORT}:${DOCKER_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
